# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.frame.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 310, 761, 231))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(510, 50, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 50, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 451, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.NumLayout = QtWidgets.QHBoxLayout()
        self.NumLayout.setObjectName("NumLayout")
        self.NumLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NumLabel.sizePolicy().hasHeightForWidth())
        self.NumLabel.setSizePolicy(sizePolicy)
        self.NumLabel.setTextFormat(QtCore.Qt.AutoText)
        self.NumLabel.setScaledContents(False)
        self.NumLabel.setObjectName("NumLabel")
        self.NumLayout.addWidget(self.NumLabel)
        self.NumLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.NumLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.NumLineEdit.setAutoFillBackground(False)
        self.NumLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NumLineEdit.setObjectName("NumLineEdit")
        self.NumLayout.addWidget(self.NumLineEdit)
        self.gridLayout.addLayout(self.NumLayout, 0, 0, 1, 1)
        self.UrlLayout = QtWidgets.QHBoxLayout()
        self.UrlLayout.setObjectName("UrlLayout")
        self.UrlLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UrlLabel.sizePolicy().hasHeightForWidth())
        self.UrlLabel.setSizePolicy(sizePolicy)
        self.UrlLabel.setTextFormat(QtCore.Qt.AutoText)
        self.UrlLabel.setScaledContents(False)
        self.UrlLabel.setObjectName("UrlLabel")
        self.UrlLayout.addWidget(self.UrlLabel)
        self.UrlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.UrlLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.UrlLineEdit.setAutoFillBackground(False)
        self.UrlLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UrlLineEdit.setObjectName("UrlLineEdit")
        self.UrlLayout.addWidget(self.UrlLineEdit)
        self.gridLayout.addLayout(self.UrlLayout, 0, 1, 1, 1)
        self.SearchUrlLayout = QtWidgets.QHBoxLayout()
        self.SearchUrlLayout.setObjectName("SearchUrlLayout")
        self.SearchUrlLabel = QtWidgets.QLabel(self.layoutWidget)
        self.SearchUrlLabel.setTextFormat(QtCore.Qt.AutoText)
        self.SearchUrlLabel.setScaledContents(False)
        self.SearchUrlLabel.setObjectName("SearchUrlLabel")
        self.SearchUrlLayout.addWidget(self.SearchUrlLabel)
        self.SearchUrlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.SearchUrlLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SearchUrlLineEdit.setAutoFillBackground(False)
        self.SearchUrlLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SearchUrlLineEdit.setObjectName("SearchUrlLineEdit")
        self.SearchUrlLayout.addWidget(self.SearchUrlLineEdit)
        self.gridLayout.addLayout(self.SearchUrlLayout, 1, 1, 1, 1)
        self.SearchLayout = QtWidgets.QHBoxLayout()
        self.SearchLayout.setObjectName("SearchLayout")
        self.SearchLabel = QtWidgets.QLabel(self.layoutWidget)
        self.SearchLabel.setTextFormat(QtCore.Qt.AutoText)
        self.SearchLabel.setScaledContents(False)
        self.SearchLabel.setObjectName("SearchLabel")
        self.SearchLayout.addWidget(self.SearchLabel)
        self.SearchLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.SearchLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SearchLineEdit.setAutoFillBackground(False)
        self.SearchLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.SearchLayout.addWidget(self.SearchLineEdit)
        self.gridLayout.addLayout(self.SearchLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "開啟下載資料夾"))
        self.pushButton_2.setText(_translate("MainWindow", "退出"))
        self.NumLabel.setText(_translate("MainWindow", "神秘六位數 :"))
        self.NumLineEdit.setPlaceholderText(_translate("MainWindow", "172991"))
        self.UrlLabel.setText(_translate("MainWindow", "網址 : "))
        self.UrlLineEdit.setPlaceholderText(_translate("MainWindow", "https://nhentai.net/g/306050/"))
        self.SearchUrlLabel.setText(_translate("MainWindow", "搜尋URL : "))
        self.SearchUrlLineEdit.setPlaceholderText(_translate("MainWindow", "https://nhentai.net/search/?q=lolicon+henreader"))
        self.SearchLabel.setText(_translate("MainWindow", "搜尋標籤 : "))
        self.SearchLineEdit.setPlaceholderText(_translate("MainWindow", "lolicon henreader"))
