# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 871)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 501, 391))
        self.frame.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 310, 761, 231))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(510, 50, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 50, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 451, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.NumLayout = QtWidgets.QHBoxLayout()
        self.NumLayout.setObjectName("NumLayout")
        self.NumLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NumLabel.sizePolicy().hasHeightForWidth())
        self.NumLabel.setSizePolicy(sizePolicy)
        self.NumLabel.setTextFormat(QtCore.Qt.AutoText)
        self.NumLabel.setScaledContents(False)
        self.NumLabel.setObjectName("NumLabel")
        self.NumLayout.addWidget(self.NumLabel)
        self.NumLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.NumLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.NumLineEdit.setAutoFillBackground(False)
        self.NumLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NumLineEdit.setObjectName("NumLineEdit")
        self.NumLayout.addWidget(self.NumLineEdit)
        self.gridLayout.addLayout(self.NumLayout, 0, 0, 1, 1)
        self.UrlLayout = QtWidgets.QHBoxLayout()
        self.UrlLayout.setObjectName("UrlLayout")
        self.UrlLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UrlLabel.sizePolicy().hasHeightForWidth())
        self.UrlLabel.setSizePolicy(sizePolicy)
        self.UrlLabel.setTextFormat(QtCore.Qt.AutoText)
        self.UrlLabel.setScaledContents(False)
        self.UrlLabel.setObjectName("UrlLabel")
        self.UrlLayout.addWidget(self.UrlLabel)
        self.UrlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.UrlLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.UrlLineEdit.setAutoFillBackground(False)
        self.UrlLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UrlLineEdit.setObjectName("UrlLineEdit")
        self.UrlLayout.addWidget(self.UrlLineEdit)
        self.gridLayout.addLayout(self.UrlLayout, 0, 1, 1, 1)
        self.SearchUrlLayout = QtWidgets.QHBoxLayout()
        self.SearchUrlLayout.setObjectName("SearchUrlLayout")
        self.SearchUrlLabel = QtWidgets.QLabel(self.layoutWidget)
        self.SearchUrlLabel.setTextFormat(QtCore.Qt.AutoText)
        self.SearchUrlLabel.setScaledContents(False)
        self.SearchUrlLabel.setObjectName("SearchUrlLabel")
        self.SearchUrlLayout.addWidget(self.SearchUrlLabel)
        self.SearchUrlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.SearchUrlLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SearchUrlLineEdit.setAutoFillBackground(False)
        self.SearchUrlLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SearchUrlLineEdit.setObjectName("SearchUrlLineEdit")
        self.SearchUrlLayout.addWidget(self.SearchUrlLineEdit)
        self.gridLayout.addLayout(self.SearchUrlLayout, 1, 1, 1, 1)
        self.SearchLayout = QtWidgets.QHBoxLayout()
        self.SearchLayout.setObjectName("SearchLayout")
        self.SearchLabel = QtWidgets.QLabel(self.layoutWidget)
        self.SearchLabel.setTextFormat(QtCore.Qt.AutoText)
        self.SearchLabel.setScaledContents(False)
        self.SearchLabel.setObjectName("SearchLabel")
        self.SearchLayout.addWidget(self.SearchLabel)
        self.SearchLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.SearchLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SearchLineEdit.setAutoFillBackground(False)
        self.SearchLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.SearchLayout.addWidget(self.SearchLineEdit)
        self.gridLayout.addLayout(self.SearchLayout, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(870, 50, 351, 311))
        self.widget.setObjectName("widget")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(540, 100, 47, 12))
        self.label_23.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_23.setObjectName("label_23")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(510, 460, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../Desktop/MyCase/nReader/icon/download_dark.ico"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../../../Desktop/MyCase/nReader/icon/download_dark.ico"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 700, 591, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "開啟下載資料夾"))
        self.pushButton_2.setText(_translate("MainWindow", "退出"))
        self.NumLabel.setText(_translate("MainWindow", "神秘六位數 :"))
        self.NumLineEdit.setPlaceholderText(_translate("MainWindow", "172991"))
        self.UrlLabel.setText(_translate("MainWindow", "網址 : "))
        self.UrlLineEdit.setPlaceholderText(_translate("MainWindow", "https://nhentai.net/g/306050/"))
        self.SearchUrlLabel.setText(_translate("MainWindow", "搜尋URL : "))
        self.SearchUrlLineEdit.setPlaceholderText(_translate("MainWindow", "https://nhentai.net/search/?q=lolicon+henreader"))
        self.SearchLabel.setText(_translate("MainWindow", "搜尋標籤 : "))
        self.SearchLineEdit.setPlaceholderText(_translate("MainWindow", "lolicon henreader"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "[Jajujo (Jovejun.)] Kiritan no Tadashii Shitsuke-kata. (VOICEROID) [Chinese] [moye个人汉化] [Digital]"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
